services:
  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
  gin:
    build: ./gin
    ports:
      - "8080:8080"
    volumes:
      - ./gin:/app
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
